apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
      name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: mysql-password
            - name: MYSQL_USER
              value: lobsters
            - name: MYSQL_DATABASE
              value: lobsters
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql
          gcePersistentDisk:
            pdName: mysql
            fsType: ext4

# EOF
